---
permalink: linux-administration/concept_host_filespec_information_for_a_particular_volume.html 
sidebar: sidebar 
keywords: snap, snapdrive, filespec, volume, host, lun 
summary: 在卷还原预览报告中， SnapDrive for UNIX 会显示 LUN 映射信息。显示的信息与检查相关，正常文件将还原。查找基于特定卷上的 LUN 的所有主机文件名非常耗时，并且会减慢卷还原过程的速度。 
---
= 特定卷的主机文件规范信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在卷还原预览报告中， SnapDrive for UNIX 会显示 LUN 映射信息。显示的信息与检查相关，正常文件将还原。查找基于特定卷上的 LUN 的所有主机文件名非常耗时，并且会减慢卷还原过程的速度。

如果您希望知道本地主机的主机文件规范信息已映射到特定存储系统卷，则可以使用 SnapDrive storage show -filervol <full-volume-name>` 。下面显示了一个示例。

[listing]
----
#snapdrive storage show -filervol bart:/vol/volusecase2

Connected LUNs and devices:

 device filename        adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdg                  -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun5          -

Host devices and file systems:

dg: vbsrfs_1_SdDg               dgtype lvm
hostvol: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv        state: AVAIL
fs: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv     mount point: /mnt/vbsrfs_1 (persistent) fstype ext3

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbe                 -     P       100m    iscsi   online   No     bart:/vol/volusecase1/lun9_0        -
/dev/sdbf                 -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun4_0        -

raw device: /dev/sdbr1  mount point: /mnt/fs11 (persistent) fstype ext3

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbr                 -     P       200m    iscsi   online   No     bart:/vol/volusecase2/fs11_SdLun    -

NFS device: bart:/vol/volusecase1        mount point: /mnt/volusecase1 (non-persistent)

LUNs not connected to this host:

 lun path                                           size   state
 -----------------------------               ------ ------
 bart:/vol/volusecase2/lunotherhost 20m   online
----