---
permalink: linux-administration/concept_storage_provisioning_for_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, vmware, vmotion, connect, lun, rdm, storage 
summary: 通过适用于 UNIX 的 SnapDrive ，您可以在 VMware VMotion 前后断开并连接 RDM LUN 。完成 VMotion 操作后，您可以执行存储系统所需的存储操作。 
---
= SnapDrive for UNIX 中支持 VMware VMotion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过适用于 UNIX 的 SnapDrive ，您可以在 VMware VMotion 前后断开并连接 RDM LUN 。完成 VMotion 操作后，您可以执行存储系统所需的存储操作。

* 关于 VMware VMotion ： *

通过 VMware VMotion ，您可以将子系统从一个 ESX 服务器移动到另一个 ESX 服务器。

要断开和连接 SnapDrive for UNIX 中的 RDM LUN ，必须执行以下操作。

* 在 VMotion 之前 *

您需要使用 SnapDrive storage disconnect` 命令删除 RDM LUN 的映射。以下语法：

` * SnapDrive storage disconnect -lun _long_lun_name LUN_name...]_*`

* 在 VMotion* 之后

完成 VMotion 后，您必须使用 SnapDrive storage connect 命令连接 RDM LUN 。以下语法：

` * SnapDrive storage connect -lun _long_lun_name LUN_name...]_*`

* 相关信息 *

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[由 SnapDrive 管理的 RDM LUN 的限制]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[配置适用于 UNIX 的 SnapDrive 的虚拟存储控制台]

xref:task_considerations_for_provisioning_rdm_luns.adoc[配置 RDM LUN 的注意事项]
