---
permalink: linux-administration/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file, name 
summary: 如果要启用日志文件，请在要启用的日志文件的名称 - 值对中指定一个文件名作为值。如果要禁用某个文件，请勿为日志文件名参数输入一个值。 
---
= 启用和禁用日志文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要启用日志文件，请在要启用的日志文件的名称 - 值对中指定一个文件名作为值。如果要禁用某个文件，请勿为日志文件名参数输入一个值。

您必须已以 root 用户身份登录。

.步骤
. 在文本编辑器中打开 `snapdrive.conf` 文件。
. 选择相应的选项以启用或禁用日志文件。
+
|===
| 如果您要 ... | 那么 ... 


 a| 
* 启用日志文件 *
 a| 
 Specify a file name as the value in the name-value pair of the log file you want to enable. SnapDrive for UNIX only writes log files if it has the name of a file to write to. The default names for the log files are as follows:
** 审核日志： `sd-audit.log`
** 恢复日志： `sd-recovery.log`
** 跟踪日志： `sd-trace.log`



NOTE: 这些文件的路径可能因主机操作系统而异。



 a| 
* 禁用日志文件 *
 a| 
 Do not enter a value for the log file name parameter. If you do not supply a value, there is no file name to which SnapDrive for UNIX can write the log information.
* 示例 * 此示例将禁用审核日志文件。`audit-log-file=""`

|===
. 进行所有更改后，请保存 `snapdrive.conf` 文件。
+
SnapDrive for UNIX 会在每次启动此文件时自动对其进行检查。要使更改生效，必须重新启动 SnapDrive for UNIX 守护进程。


