---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: 要在 SnapDrive for UNIX 中使用多路径，必须完成包括安装和启动 HBA 在内的步骤。如果您使用的是非 NetApp 多路径解决方案，则必须从 HBA 供应商的网站下载软件和应用程序包。 
---
= 启用多路径
:icons: font
:imagesdir: ../media/


[role="lead"]
要在 SnapDrive for UNIX 中使用多路径，必须完成包括安装和启动 HBA 在内的步骤。如果您使用的是非 NetApp 多路径解决方案，则必须从 HBA 供应商的网站下载软件和应用程序包。

您的系统必须运行当前版本的 FC 和 iSCSI 系统组件。

http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"]

.步骤
. 在安装相应的 Host Utilities 软件之前，请先安装支持的 HBA 。
+

NOTE: 适用于 UNIX 的 SnapDrive 支持多供应商 HBA 。

. 启动 HBA 服务。
+
如果 HBA 服务未运行，则在运行 SnapDrive for UNIX 命令时会显示以下错误消息，例如 SnapDrive storage create` 和 SnapDrive config prepare LUNs` ：

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
您必须验证所需数量的路径是否已启动且正在运行。您可以使用 Host Utilities 软件附带的 `sanlun` 实用程序验证路径。例如，在 FC 多路径配置中，您可以使用 `sanlun fcp show adapter -v` 命令。

+
在以下示例中，有两个 HBA 端口（ fcd0 和 fcd1 ）连接到运行正常的主机（端口状态）。您只能有一个 HBA 或 iSCSI 启动程序，并且必须通过为目标 LUN 提供多个路径来配置多路径。

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
如果在主机上启用了多路径，则可以为同一 LUN 显示多个路径。您可以使用 `sanlun lun show all` 命令验证路径。在以下示例中，您可以找到指向同一 LUN 的多个路径（`鱼： /vol/vol1/lun` ）：

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. 如果 SnapDrive for UNIX 或 Host Utilities 支持第三方多路径解决方案，请从 HBA 供应商的网站下载 HBA 驱动程序软件包和应用程序包。 * QLogic * ：对于 QLogic HBA ，请转至 http://support.qlogic.com/[]。在 OEM 型号中，选择 NetApp 。找到支持表中列出的驱动程序版本并下载。* Emulex ： * 对于 Emulex HBA ，请转至。从 "Downloads" 中选择 "NetApp" 。找到支持表中列出的驱动程序版本并下载。同时，从同一位置下载 Emulex 应用程序软件包。
+
如果您使用的是具有 FC 连接的 QLogic 适配器，请从 QLogic 网站下载 QLogic 重新扫描脚本并将其复制到 ` 或 root` 路径（例如， ` /root/dynamic-lun-rescan` ）。QLogic 重新扫描脚本会要求用户确认； SnapDrive for UNIX 可能会在此确认阶段无限期挂起。您可以通过在脚本中将变量 ` QL_disable_warning_` 设置为 `1` 来避免此确认。

+
早期版本的 SnapDrive for UNIX 使用供应商专用的 SCSI 重新扫描脚本通过 FC 扫描 LUN ，从而将供应商专用脚本复制到 ` /root/dynamic-lun-rescan 。 sh` 。此功能在 RHEL 5U3 之前一直可用。

+
对于 RHEL 5U4/SLES 10SP2 及更高版本， ` /usr/bin` 目录中当前提供了重新扫描脚本。如果目录中没有重新扫描脚本，则该脚本会与 `sg3_utils` 软件包一起存在。

+

NOTE: 您必须确保 `sg3_utils` 和 `sg3_utils-libs` 库可用于 Red Hat Enterprise Linux （ RHEL ）和 Oracle Enterprise Linux （ OEL ）版本。但是， `scSCI utility.rpm` 软件包中的 `sg3_utils` 库可用于 SUSE Linux Enterprise Server （ SLES ）版本。

. 在 FC 配置中，使用交换机分区配置对主机 HBA 端口和目标端口进行分区。
. 安装并设置相应的 FC 交换机。
. 检查 SnapDrive for UNIX 堆栈要求。
. 安装或升级适用于 UNIX 的 SnapDrive 。
. 验证 SnapDrive for UNIX 安装。
. 找到 `snapdrive.conf` 文件路径。
. 在 `snapdrive.conf` 文件中配置以下配置变量：
+
** ` 多路径类型 _`
** `` default-transport_
** ` fsttype_`
** ` vmtype_`
+
对于每台主机，多路径类型，传输类型，文件系统和卷管理器类型彼此相关。下表介绍了所有可能的组合：

+
|===
| 主机平台 | 默认传输类型 | 多路径类型 | FSType | vmtype 


 a| 
Linux
 a| 
iSCSI
 a| 
nativempio
 a| 
ext4 或 ext3
 a| 
LVM



 a| 
iSCSI
 a| 
无
 a| 
ext4 或 ext3
 a| 
LVM



 a| 
FCP
 a| 
无
 a| 
ext4 或 ext3
 a| 
LVM



 a| 
FCP
 a| 
nativempio
 a| 
ext4 或 ext3
 a| 
LVM

|===
+
上表提供了 ` multipathing-type_` ， ` default-transport_` ， ` fsttype_` 和 ` vmtype_` 配置变量支持的值。

+

NOTE: 如果传输协议为 `iscsi` ，而多路径类型设置为 `none` ，则应停止多路径守护进程并执行 SnapDrive for UNIX 命令。



. 保存 `snapdrive.conf` 文件。
+
SnapDrive for UNIX 会在每次启动此文件时自动对其进行检查。要使更改生效，必须重新启动 SnapDrive for UNIX 守护进程。



* 相关信息 *

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[迁移多路径类型后， SnapRestore 和 Snapconnect 操作在 Linux 中不起作用]

http://mysupport.netapp.com["NetApp 支持"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互操作性"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["《 Linux Unified Host Utilities 7.1 安装指南》"]
