---
permalink: linux-installation-7mode/reference_where_to_go_next.html 
sidebar: sidebar 
keywords: snap, snapdrive, after, configure, create, copy 
summary: 配置 SnapDrive for UNIX 并创建 Snapshot 副本后，您可以执行还原操作，连接 Snapshot 副本并创建克隆。您还可以了解其他重要的 SnapDrive 功能，例如基于角色的访问控制 \ （ RBAC ），增强型克隆拆分和基于卷的 SnapRestore 。 
---
= 下一步行动
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置 SnapDrive for UNIX 并创建 Snapshot 副本后，您可以执行还原操作，连接 Snapshot 副本并创建克隆。您还可以了解其他重要的 SnapDrive 功能，例如基于角色的访问控制（ Role-Based Access Control ， RBAC ），增强型克隆拆分和基于卷的 SnapRestore 。

您可以在以下文档中找到有关这些功能的详细信息，以及有关 SnapDrive for UNIX 的特定版本信息，这些文档可从 NetApp 支持站点获得：

* link:../linux-administration/index.html["《适用于 Linux 的 SnapDrive 5.3.2 for UNIX 管理指南》"]
+
介绍部署完成后如何在 SnapDrive for UNIX 上配置各种功能。主题包括如何配置 igroup ，配置适用于 UNIX 的 SnapDrive ，配置 RBAC 以及使用数据收集实用程序诊断 SnapDrive for UNIX 的问题。

* https://library.netapp.com/ecm/ecm_download_file/ECMLP2849339["《 SnapDrive 5.3.2 for UNIX 发行说明》（ AIX ， Linux 和 Solaris ）"]
+
介绍适用于 UNIX 的 SnapDrive 5.3.2 的新增功能，重要注意事项，已知问题和限制。

* https://library.netapp.com/ecm/ecm_download_file/ECMP12471545["《适用于 UNIX 的 SnapManager 3.4 for Oracle 安装和设置指南》，适用于在 7- 模式下运行的 Data ONTAP"]
+
介绍在 UNIX 环境中使用 7- 模式部署 SnapManager for Oracle 时必须执行的初始任务。主题包括如何安装和配置产品以及如何备份数据库。

* link:https://www.netapp.com/pdf.html?item=/media/16322-tr-4212.pdf["NetApp 技术报告 4212 ：《适用于 UNIX 的 SnapDrive 5.3 最佳实践指南》"]
+
介绍 SnapDrive for UNIX 最佳实践。


