---
permalink: aix/concept_considerations_when_working_with_snapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, considerations, snapshot, copy 
summary: 在使用 Snapshot 副本时，应牢记一些注意事项，例如 SnapDrive for UNIX 仅适用于其创建的 Snapshot 副本，或者 Snapshot 副本自动从存储系统复制到主机等。 
---
= 使用 Snapshot 副本时的注意事项
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 Snapshot 副本时，应牢记一些注意事项，例如 SnapDrive for UNIX 仅适用于其创建的 Snapshot 副本，或者 Snapshot 副本自动从存储系统复制到主机等。

使用 Snapshot 操作时，应考虑以下事项：

* SnapDrive for UNIX 仅适用于其创建的 Snapshot 副本。
+
它无法还原未创建的 Snapshot 副本。

* 在目标存储系统上创建 Snapshot 副本时， Snapshot 副本会自动从创建该副本的源存储系统复制到目标存储系统。
+
通过 SnapDrive for UNIX ，您还可以还原目标存储系统上的 Snapshot 副本。

* 如果您使用 SnapDrive snap connect` 命令在上次连接（或仍连接）的主机上的新位置连接到 Snapshot 副本，则会连接到源主机。
* 对跨多个存储系统卷或多个存储系统的存储实体的 Snapshot 支持仅限于不允许在软件堆栈中执行冻结操作的配置。
* 通过 NFS 协议导出卷时，必须将匿名用户 ID 选项设置为 0 ， SnapDrive for UNIX 命令才能正常运行。
* 如果一个磁盘组中有两个 JFS 文件系统（ JFS 和 JFS2 ），则 SnapDrive for UNIX 仅支持对 JFS2 文件系统执行操作。
* 通过 SnapDrive for UNIX ，您可以创建并发卷组的 Snapshot 副本，以及使用相同属性克隆或还原。
* 在创建 Snapshot 副本后立即执行单文件 SnapRestore （ SFSR ）操作失败。
+
必须在经过一段时间后重试此操作。有关详细信息，请参见 link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/home.html["《集群模式 Data ONTAP 逻辑存储管理指南》"]。


