---
permalink: aix/reference_exit_status_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, exit, status, value 
summary: 每个退出状态值都有一个错误名称以及与其关联的类型。查看此表以了解退出状态值，错误名称，类型和问题描述。 
---
= 退出状态值
:icons: font
:imagesdir: ../media/


[role="lead"]
每个退出状态值都有一个错误名称以及与其关联的类型。查看此表以了解退出状态值，错误名称，类型和问题描述。

下表包含有关退出状态值的信息。退出状态值按顺序编号。如果 SnapDrive for UNIX 当前未实施错误，则此表不会包含此退出状态值。因此，这些数字可能会有一定的差距。

|===
| 退出值 | 错误名称 | Type | Description 


 a| 
1.
 a| 
不支持
 a| 
命令错误
 a| 
已调用此版本的 SnapDrive for UNIX 不支持的函数。



 a| 
2.
 a| 
无内存
 a| 
致命
 a| 
系统内存已用尽。只有释放足够的内存才能使 SnapDrive for UNIX 正常工作，才能继续运行。检查其他正在运行的应用程序，确认它们不会占用过多的内存。



 a| 
3.
 a| 
命令无效
 a| 
命令错误
 a| 
您发出的命令无效；这可能是您输入的命令文本中的语法错误。



 a| 
4.
 a| 
已存在
 a| 
命令错误
 a| 
您请求创建已存在的内容。通常，此错误是指 Snapshot 副本名称，该名称不能位于要创建 Snapshot 副本的存储系统卷上。



 a| 
5.
 a| 
创建线程失败
 a| 
管理员错误
 a| 
SnapDrive for UNIX 无法创建进程线程。检查系统上运行的其他进程，以确保有足够的线程资源可用。



 a| 
6.
 a| 
未找到
 a| 
命令错误
 a| 
您在 SnapDrive for UNIX 命令行中包含了不存在的文件，数据组，主机卷，文件系统或其他参数。



 a| 
7.
 a| 
不是挂载的文件系统
 a| 
命令错误
 a| 
要访问的文件系统不是有效的文件系统或未挂载。



 a| 
9
 a| 
卷管理器错误
 a| 
命令错误
 a| 
访问卷管理器时返回错误。请参见特定错误消息，以获取有关哪个错误以及原因的详细信息。



 a| 
10
 a| 
名称无效
 a| 
命令错误
 a| 
您在命令行上提供的名称格式不正确。

例如，未将存储系统卷指定为 `filer ： /vol/vol_name` 。如果在基于存储系统或卷管理器的名称中指定了无效字符，则也会出现此消息。



 a| 
11.
 a| 
未找到设备
 a| 
管理员错误
 a| 
SnapDrive for UNIX 无法访问要为其创建 Snapshot 副本的磁盘组中的 LUN 。

检查主机和存储系统上所有 LUN 的状态。另请检查存储系统卷是否联机，以及存储系统是否已启动并连接到主机。



 a| 
12
 a| 
繁忙
 a| 
命令错误
 a| 
LUN 设备，文件，目录，磁盘组，主机卷， 或其他实体处于繁忙状态。

这通常是一个非致命错误，在您重试此命令时会消失。有时，它会指示某个资源或进程挂起，从而导致此对象处于繁忙状态且不可用，无法供 SnapDrive for UNIX 使用。

它还可能指示您在 I/O 流量过大而无法成功创建 Snapshot 副本的时间段内尝试创建 Snapshot 副本。



 a| 
13
 a| 
无法初始化
 a| 
致命
 a| 
SnapDrive for UNIX 无法初始化所需的第三方资料。这可以是指文件系统，卷管理器，主机集群软件，多路径软件等。



 a| 
14
 a| 
SnapDrive 繁忙
 a| 
SnapDrive 繁忙
 a| 
另一个用户或进程正在同一主机或存储系统上执行操作，而您要求 SnapDrive for UNIX 执行此操作。重试此操作。

有时，此消息表示另一个进程已挂起，您必须将其终止。


NOTE: 在某些情况下， Snapshot 还原操作可能需要很长时间。请确保您认为挂起的过程不仅仅是等待 Snapshot 还原操作完成。



 a| 
15
 a| 
配置文件错误
 a| 
致命
 a| 
SnapDrive.conf 文件中的条目无效，不足或不一致。有关详细信息，请参见特定的错误消息。必须更正此文件， SnapDrive for UNIX 才能继续。



 a| 
17
 a| 
权限错误
 a| 
命令错误
 a| 
您无权执行此命令。要运行适用于 UNIX 的 SnapDrive ，您必须以 root 用户身份登录。



 a| 
18
 a| 
无存储器
 a| 
管理员错误
 a| 
SnapDrive for UNIX 无法联系此命令所需的存储系统。检查错误消息中指示的与存储系统的连接。



 a| 
19
 a| 
存储器登录错误
 a| 
管理员错误
 a| 
SnapDrive for UNIX 无法使用您提供的登录信息登录到存储系统。



 a| 
20
 a| 
许可证错误
 a| 
管理员错误
 a| 
SnapDrive for UNIX 所需的服务未获得在此存储系统上运行的许可。



 a| 
22.
 a| 
无法冻结 FS
 a| 
管理员错误
 a| 
Snapshot 创建操作失败，因为 SnapDrive for UNIX 无法冻结指定的文件系统以创建 Snapshot 副本。确认系统 I/O 流量足够轻，足以冻结文件系统，然后重试此命令。



 a| 
27
 a| 
Snapshot 副本不一致
 a| 
管理员错误
 a| 
Snapshot 还原操作失败，因为您请求从磁盘组映像不一致的 Snapshot 副本进行还原。在以下情况下，可能会出现映像不一致的情况：

* 您未使用 SnapDrive for UNIX 创建 Snapshot 副本。
* Snapshot 创建操作在设置一致的位之前中断，因此无法清理（如发生灾难性系统故障）。
* 创建 Snapshot 副本后， Snapshot 副本发生某种类型的数据问题。




 a| 
28
 a| 
HBA 故障
 a| 
管理员错误
 a| 
SnapDrive for UNIX 在尝试从 HBA 检索信息时遇到错误。



 a| 
29
 a| 
元数据错误
 a| 
管理员错误
 a| 
SnapDrive for UNIX 在创建 Snapshot 副本时写入的 Snapshot 副本元数据发生错误。



 a| 
30 个
 a| 
无 Snapshot 副本元数据
 a| 
管理员错误
 a| 
SnapDrive for UNIX 无法执行 Snapshot 还原操作，因为元数据不包含所有请求的磁盘组。



 a| 
31
 a| 
密码文件错误
 a| 
管理员错误
 a| 
此密码文件的条目错误。使用 SnapDrive config delete` 命令删除此存储系统的登录条目。然后使用 SnapDrive config set _user_name_` 命令重新输入登录信息。



 a| 
33
 a| 
无密码文件条目
 a| 
管理员错误
 a| 
此密码文件没有此存储系统的条目。对需要运行 SnapDrive for UNIX 的每个存储系统运行 SnapDrive config set _username filername_` 命令。然后重试此操作。



 a| 
34
 a| 
不是 NetAPPLUn
 a| 
管理员错误
 a| 
SnapDrive for UNIX 命令遇到的 LUN 不在 NetApp 存储系统上。



 a| 
35
 a| 
用户已中止
 a| 
管理员错误
 a| 
系统显示一个提示，要求您确认操作，您表示不希望执行此操作。



 a| 
36
 a| 
I/O 流错误
 a| 
管理员错误
 a| 
系统输入或系统输出例程返回了 SnapDrive for UNIX 无法识别的错误。

运行 SnapDrive.dc 并将此信息发送给 NetApp 技术支持，以便他们可以帮助您确定要执行的步骤以完成恢复。



 a| 
37
 a| 
文件系统已满
 a| 
管理员错误
 a| 
尝试写入文件失败，因为文件系统上的空间不足。当您在相应的文件系统上释放足够的空间时， SnapDrive for UNIX 可以继续。



 a| 
38
 a| 
文件错误
 a| 
管理员错误
 a| 
当 SnapDrive for UNIX 读取或写入系统配置文件或临时文件时发生 I/O 错误。



 a| 
39
 a| 
磁盘组重复
 a| 
命令错误
 a| 
尝试激活磁盘组时， SnapDrive for UNIX 获得了重复的次要节点编号。



 a| 
40
 a| 
文件系统解冻失败。
 a| 
管理员错误
 a| 
由于文件系统上的系统活动， snap create 命令失败。如果 Snapshot 副本所需的 SnapDrive for UNIX 文件系统冻结在 Snapshot 副本完成之前超时，通常会发生这种情况。



 a| 
43
 a| 
名称已在使用中
 a| 
命令错误
 a| 
SnapDrive for UNIX 已尝试创建磁盘组，主机卷，文件系统或 LUN ，但此名称已在使用中。要更正此错误，请选择一个未使用的名称，然后重新输入 SnapDrive for UNIX 命令。



 a| 
44
 a| 
文件系统管理器错误
 a| 
致命
 a| 
在以下情况下， SnapDrive for UNIX 在文件系统中遇到意外错误：

* 正在尝试创建文件系统
* 在文件系统挂载表中创建一个条目，以便在启动时自动挂载文件系统。


随此代码显示的错误消息文本描述了文件系统遇到的错误。记录此消息并将其发送给 NetApp 技术支持，以便他们能够帮助您确定要执行的步骤以完成恢复。



 a| 
45
 a| 
挂载点错误
 a| 
管理员错误
 a| 
文件系统挂载点出现在系统挂载表文件中。要更正此错误，请选择未使用或未在挂载表中列出的挂载点，然后重新输入 SnapDrive for UNIX 命令。



 a| 
46
 a| 
未找到 LUN
 a| 
命令错误
 a| 
SnapDrive for UNIX 命令尝试访问存储系统上不存在的 LUN 。

要进行更正，请检查 LUN 是否存在以及是否正确输入了 LUN 的名称。



 a| 
47
 a| 
未找到启动程序组
 a| 
管理员错误
 a| 
无法按预期访问存储系统启动程序组。因此， SnapDrive for UNIX 无法完成当前操作。

具体的错误消息介绍了问题以及解决问题所需执行的步骤。修复此问题，然后重复此命令。



 a| 
48
 a| 
对象脱机
 a| 
管理员错误
 a| 
SnapDrive for UNIX 尝试访问某个对象（例如卷），但由于该对象处于脱机状态而失败。



 a| 
49
 a| 
实体冲突
 a| 
命令错误
 a| 
SnapDrive for UNIX 尝试创建 igroup ，但遇到名称相同的 igroup 。



 a| 
50
 a| 
清理错误
 a| 
致命
 a| 
SnapDrive for UNIX 遇到了一个应删除但仍存在的项目。



 a| 
51
 a| 
磁盘组 ID 冲突
 a| 
命令错误
 a| 
SnapDrive snap connect` 命令请求的磁盘组 ID 与现有磁盘组冲突。

这通常意味着，在不支持 SnapDrive snap connect` 命令的系统上尝试在发起主机上执行该命令。要修复此问题，请尝试从其他主机执行此操作。



 a| 
52
 a| 
LUN 未映射到任何主机
 a| 
管理员错误
 a| 
LUN 未映射到任何主机。换言之，它不属于存储系统启动程序组。要访问 LUN ，必须将 LUN 映射到 SnapDrive for UNIX 以外的当前主机。



 a| 
53.
 a| 
LUN 未映射到本地主机
 a| 
管理员错误
 a| 
LUN 未映射到当前主机。换言之，它不属于包含当前主机启动程序的存储系统启动程序组。要访问 LUN ，必须将 LUN 映射到 SnapDrive for UNIX 以外的当前主机。



 a| 
54
 a| 
LUN 使用外部 igroup 进行映射
 a| 
管理员错误
 a| 
LUN 使用外部存储系统启动程序组进行映射。换言之，它属于仅包含在本地主机上未找到的启动程序的存储系统 igroup 。

因此， SnapDrive for UNIX 无法删除此 LUN 。

要使用适用于 UNIX 的 SnapDrive 删除 LUN ， LUN 必须仅属于本地 igroup ；即，仅包含在本地主机上找到的启动程序的 igroup 。



 a| 
55
 a| 
LUN 使用混合 igroup 进行映射
 a| 
管理员错误
 a| 
LUN 使用混合存储系统启动程序组进行映射。换言之，它属于一个存储系统 igroup ，其中包含在本地主机上找到的启动程序和在该主机上未找到的启动程序。

因此， SnapDrive for UNIX 无法断开 LUN 的连接。

要使用 SnapDrive for UNIX 断开 LUN 的连接， LUN 必须仅属于本地 igroup 或外部 igroup ，而不是混合 igroup 。（本地 igroup 仅包含在本地主机上找到的启动程序；外部 igroup 包含在本地主机上未找到的启动程序。）



 a| 
56
 a| 
Snapshot 副本还原失败
 a| 
管理员错误
 a| 
SnapDrive for UNIX 已尝试执行 Snapshot 还原操作，但在未还原 Snapshot 副本中的任何 LUN 的情况下，此操作失败。

具体的错误消息介绍了问题以及解决问题所需执行的步骤。修复此问题，然后重复此命令。



 a| 
58
 a| 
需要重新启动主机
 a| 
管理员错误
 a| 
主机操作系统需要重新启动才能更新内部数据。SnapDrive for UNIX 已为此更新准备好主机，但无法完成当前操作。

重新启动主机，然后重新输入导致显示此消息的 SnapDrive for UNIX 命令行。重新启动后，该操作将能够完成。



 a| 
59
 a| 
主机，需要准备 LUN
 a| 
管理员错误
 a| 
主机操作系统需要更新内部数据才能完成当前操作。要创建新的 LUN ，需要进行此更新。

SnapDrive for UNIX 无法执行更新，因为已禁用主机自动配置准备，因为 `snapdrive.conf` 变量 ` _enable-implicate-host-preparation_` 设置为 "`off` " 。在禁用自动主机准备的情况下，您应使用 lun config prepare SnapDrive 命令来准备主机以配置 LUN ，或者手动执行准备步骤。

要避免此错误消息，请在 `snapdrive.conf` 文件中将 ` enable-implicate-host-preparation_` 值设置为 "`on` " 。



 a| 
62.
 a| 
不为空
 a| 
命令错误
 a| 
发生错误的原因是， SnapDrive for UNIX 无法删除存储系统卷或目录。如果其他用户或其他进程在 SnapDrive 尝试删除的同一目录中同时创建文件，则可能会发生这种情况。要避免此错误，请确保一次只能有一个用户使用存储系统卷。



 a| 
63.
 a| 
超时已过期
 a| 
命令错误
 a| 
发生错误的原因是， SnapDrive for UNIX 无法在 50 分钟的超时时间段内还原 LUN 。

记录此消息并将其发送给 NetApp 技术支持，以便他们能够帮助您确定要执行的步骤以完成恢复。



 a| 
64
 a| 
服务未运行
 a| 
管理员错误
 a| 
发生错误的原因是， SnapDrive for UNIX 命令指定了一个 NFS 实体，而存储系统未运行 NFS 服务。



 a| 
126.
 a| 
未知错误
 a| 
管理员错误
 a| 
发生了可能很严重的未知错误。运行 `snapdrive.dc` 实用程序，并将其结果发送给 NetApp 技术支持进行分析。



 a| 
127.
 a| 
内部错误
 a| 
致命
 a| 
发生 SnapDrive for UNIX 内部错误。运行 `snapdrive.dc` 并将其结果发送给 NetApp 技术支持进行分析。

|===