---
permalink: aix/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy 
summary: 命令 SnapDrive snap show 或 list 可显示创建 Snapshot 副本的存储系统的名称，主机名，日期和时间等。 
---
= 显示 Snapshot 副本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
命令 SnapDrive snap show` 或 `list` 可显示创建 Snapshot 副本的存储系统的名称，主机名，日期和时间等。

.步骤
. 输入以下命令语法以显示 Snapshot 副本：
+
` * SnapDrive snap show （ -snapname] _long_snap_name_ [_snap_name_...] 【 -verbose 】 *`



此操作至少会显示有关 Snapshot 副本的以下信息：

* 创建 Snapshot 副本的存储系统的名称
* 创建 Snapshot 副本的主机的名称
* 存储系统上 LUN 的路径
* 创建 Snapshot 副本的日期和时间
* Snapshot 副本的名称
* Snapshot 副本中包含的磁盘组的名称


* 示例 * ：以下是 SnapDrive snap show` 命令的示例：

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
* 示例 * ：此示例使用通配符显示有关特定卷上可用 Snapshot 副本的信息：

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
* 示例 * ：在此示例中， AIX 主机的命令行使用了 ` -verbose` 选项：

[listing]
----
# snapdrive snap list betty:/vol/vol1:testsnap -v
snap name host date
snapped
------------------------------------------------------------------
-------------
betty:/vol/vol1:testsnap aix198-75 Jul 31
10:43 test1_SdDg
host OS: AIX 3 5
snapshot name: testsnap
Volume Manager: aixlvm 5.3
disk group: test1_SdDg
host volume: test1_SdHv
file system: test1_SdHv file system type: jfs2
mountpoint:
/mnt/test1
lun path dev paths
-------------------------------------------------------
betty:/vol/vol1/aix198-75_luntest1_SdLun /dev/hdisk32
----
* 示例 * ：此示例包含有关 AIX 主机上未使用 SnapDrive for UNIX 创建的 Snapshot 副本的消息：

[listing]
----
# snapdrive snap show -filer toaster
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:hourly.0 non-snapdrive snapshot
toaster:/vol/vol1:snap1 DBserver1 Oct 01 13:42 dg1
dg2
toaster:/vol/vol1:snap2 DBserver2 Oct 10 13:40
DBdg/hvol1
toaster:/vol/vol1:snap3 DBserver3 Oct 31 13:45
DBdg
----
此示例使用 SnapDrive snap show` 命令和 ` - verbose` 选项显示 AIX 主机上基于 LVM 的文件系统的 Snapshot 副本：

[listing]
----
# snapdrive snap show -v -fs /mnt/check_submit/csdg2/hv3_0
snapname host date snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:mysnapshot sales-aix Aug 24 10:55 csdg2
host OS: AIX 1 5
snapshot name: mysnapshot
Volume Manager: aixlvm 5.1
disk group: csdg2
host volume: csdg2_log
host volume: csdg2_hv3_0
file system: csdg2_hv3_0 file system type: jfs2 mountpoint:
/mnt/check_submit/csdg2/hv3_0
lun path dev paths
-------------------------------------------------------
spinel:/vol/vol1/check_submit_aix-4 /dev/hdisk4
----
* 示例 * ：以下示例使用通配符：

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
* 示例 * ：在此示例中，使用通配符无效，因为通配符位于名称中间，而不是置于末尾：

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----