---
permalink: solaris/reference_informationrequired_for_the_storagecreate_operation.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, create, operation, information, requirement 
summary: 完成存储创建操作后，您必须提供一些信息。 
---
= 存储创建操作所需的信息
:icons: font
:imagesdir: ../media/


[role="lead"]
完成存储创建操作后，您必须提供一些信息。

下表列出了使用 SnapDrive storage create` 命令创建存储时需要提供的信息：

|===
| 要求 | 参数 


 a| 
确定要配置的存储类型。根据您输入的命令，您可以创建以下任意项：

* LUN
+
如果创建一个或多个 LUN ，则第一个参数必须使用长形式的 LUN 名称，此名称用于指定存储系统名称，卷名称以及卷中 LUN 的名称。

+
要指定其他 LUN ，如果新 LUN 与上一个 LUN 位于同一存储系统和卷上，则可以单独使用 LUN 名称（简称）。否则，您可以指定新的存储系统名称和卷名称（或仅指定卷名称）来替换先前的值。

* 直接在 LUN 上创建的文件系统
+
如果在 LUN 上创建文件系统，则第一个参数必须是 ` _-FS_` 挂载点。要在存储系统和卷中的 LUN 上创建文件系统，请使用 ` -filervol_` 参数并指定存储系统和卷的名称。要在特定 LUN 上创建文件系统，请使用 ` _-lun_` 参数并指定存储系统名称，卷名称和 LUN 名称。您还必须包括 ` -nolvm` 选项，才能在 LUN 上创建文件系统，而无需激活主机 LVM 。

+
默认情况下， SnapDrive for UNIX 会自动执行与 LUN 的主机准备和发现以及映射和连接相关的所有任务。

* 包含主机卷和文件系统的 LVM 磁盘组
+
指定磁盘或卷组，文件系统，主机或逻辑卷时， SnapDrive for UNIX 将执行创建所指定实体所需的所有操作。您可以明确指定 LUN ，也可以仅提供存储系统和卷信息，并让 SnapDrive for UNIX 自动创建 LUN 。

+
如果要创建文件系统等实体，则无需为磁盘或卷组提供值。SnapDrive for UNIX 会自动创建一个。





 a| 
* LUN （ -LUN ）

 a| 
` * lun_name*`



 a| 
* 其他 LUN

 a| 
` * lun_name*` （长或短格式）



 a| 
* 磁盘组（` -dg * dgname*` ）或卷组（` -vg * vgname*` ）

 a| 
` * 磁盘 *` 或 ` * 卷组名称 *`



 a| 
SnapDrive for UNIX 会根据您使用 ` -DG` 选项输入的值创建一个磁盘或卷组来存放 LUN 。您为组提供的名称不能存在。



 a| 
* 主机卷（` -hostvol * file_spec*` ）或逻辑卷（` -lvol * file_spec*` ）

 a| 
` * 主机 *` 或 ` * 逻辑卷名称 *`



 a| 
* 文件系统（` -fs * 文件规范 *` ）

 a| 
` * 文件系统名称 *`



 a| 
` -nolvm`
 a| 
~



 a| 
* 必需： * 如果要创建直接驻留在 LUN 上的文件系统，请指定 ` -nolvm` 选项。



 a| 
* LUN 大小（` -lunsize` ）

 a| 
` * 大小 *`



 a| 
* 磁盘组大小（` -dgsize` ）
* 卷组大小（` -vgsize` ）

 a| 
` * 大小 *`



 a| 
为要创建的每个实体指定大小（以字节为单位）或其他一些数据单元。LVM 实体的大小取决于您请求的 LUN 的聚合大小。

要控制主机实体的大小，请使用 ` -dgsize` 选项指定底层磁盘组的大小（以字节为单位）。



 a| 
* 存储系统卷的路径（` -filervol` ）

 a| 
` * lor_filer_path*`



 a| 
* ` LUN`

 a| 
` * lun_path*`



 a| 
指定希望 SnapDrive for UNIX 自动在其中创建 LUN 的存储系统及其卷。

* 使用 ` -filervol` 选项指定要在其中创建 LUN 的存储系统和卷。
+
请勿指定 LUN 。当您使用此形式的 SnapDrive storage create` 命令时，适用于 UNIX 的 SnapDrive 会自动创建 LUN 。它会使用系统默认值来确定 LUN ID 以及每个 LUN 的大小。它将关联磁盘 / 卷组的名称基于主机卷或文件系统的名称。

* 使用 ` -lun` 选项为要使用的 LUN 命名。




 a| 
文件系统类型（` -fstype` ）
 a| 
` * 类型 *`



 a| 
如果要创建文件系统，请提供表示文件系统类型的字符串。

对于 Solaris ， SnapDrive for UNIX 可接受： `VxFS` 或 `UFS` 。


NOTE: 默认情况下，如果主机平台只有一种文件系统类型，则 SnapDrive for UNIX 将提供此值。在这种情况下，您无需输入它。



 a| 
` -vmtype`
 a| 
` * 类型 *`



 a| 
* 可选： * 指定用于 SnapDrive for UNIX 操作的卷管理器类型。



 a| 
` -fsopts`
 a| 
` * 选项名称和值 *`



 a| 
` - mntopts`
 a| 
` * 选项名称和值 *`



 a| 
` - noperit`
 a| 
~



 a| 
` 预留 | -noreserve`
 a| 
~



 a| 
* 可选： * 如果要创建文件系统，可以指定以下选项：

* 使用 ` -fsopts` 指定要传递到用于创建文件系统的 host 命令的选项。例如，您可以提供 `mkfs` 命令将使用的选项。您提供的值通常需要使用带引号的字符串，并且必须包含要传递到命令的确切文本。
* 使用 ` -mntopts` 指定要传递到主机挂载命令的选项（例如，指定主机系统日志记录行为）。指定的选项存储在主机文件系统表文件中。允许的选项取决于主机文件系统类型。
+
` -mntopts` 参数是使用 `mount` command ` -o` 标志指定的文件系统 ` 类型` 选项。请勿在 ` -mntopts` 参数中包含 ` -o` 标志。例如，序列 ` -mntopts tmplog` 会将字符串 ` -o tmplog` 传递到 `mount` 命令，并在新命令行中插入文本 tmplog 。

+

NOTE: 如果为存储和快照操作传递任何无效的 ` -mntopts` 选项，则 SnapDrive for UNIX 不会验证这些无效的挂载选项。

* 使用 ` -noper` 创建文件系统，而不向主机上的文件系统挂载表文件添加条目。默认情况下， SnapDrive storage create` 命令会创建永久性挂载。在 Solaris 主机上创建 LVM 存储实体时， SnapDrive for UNIX 会自动创建存储，挂载文件系统，然后在主机文件系统表中为文件系统放置一个条目。
* 使用 ` -reserve | -noreserve` 创建存储，无论是否创建空间预留。




 a| 
` 设备类型`
 a| 
~



 a| 
` -DeviceType` 选项指定用于 SnapDrive for UNIX 操作的设备类型。此类型可以是 "Shared" （共享），即将 LUN ，磁盘组和文件系统的范围指定为集群范围的主机，也可以是 "dedicated " （专用），即将 LUN ，磁盘组和文件系统的范围指定为 "local" （本地）。

尽管存储创建过程是从主机集群主节点启动的，但必须在每个主机集群节点上执行 LUN 发现和 LUN 的主机准备工作。因此，您应确保所有主机集群节点上都允许 SnapDrive for UNIX 使用 rsh 或 ssh access-without 密码提示符。

您可以使用 SFRAC 管理命令查找当前集群主节点。` -DeviceType` 选项指定用于 SnapDrive for UNIX 操作的设备类型。如果未在 SnapDrive for UNIX 命令中指定支持此选项的 ` -DeviceType` 选项，则相当于指定 ` -DeviceType dedicated` 。



 a| 
* igroup 名称（` * -igroup*` ）

 a| 
` * ig_name*`



 a| 
* 可选： * NetApp 建议您使用主机的默认 igroup ，而不是提供 igroup 名称。

|===